spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: true


logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
      com:
        example: DEBUG